CREATE TABLE
  public.br_data_cons (
    "Date" text NULL,
    "Nasscom Status" text NULL,
    "Nasscom Member Status" text NULL,
    "Account Global Legal Name" text NULL,
    "About Company" text NULL,
    "HQ Address" text NULL,
    "HQ City" text NULL,
    "HQ State" text NULL,
    "HQ ZIP Code" text NULL,
    "HQ Country" text NULL,
    "HQ Region" text NULL,
    "HQ Broad Line" text NULL,
    "HQ Website" text NULL,
    "Linkedin Link" text NULL,
    "HQ Offerings" text NULL,
    "Source Link HQ Offering" text NULL,
    "HQ Sub Industry" text NULL,
    "HQ Industry" text NULL,
    "Primary Category" text NULL,
    "Primary Nature" text NULL,
    "HQ Forbes Rank 2024" text NULL,
    "HQ Fortune Rank 2024" text NULL,
    "HQ Company Type" text NULL,
    "HQ Revenue in USD Mil" text NULL,
    "HQ Revenue Range" text NULL,
    "HQ FY End" text NULL,
    "HQ Revenue Year" text NULL,
    "Source Type HQ Revenue" text NULL,
    "Source Link HQ Revenue" text NULL,
    "HQ Employee Count" text NULL,
    "HQ Employee Range" text NULL,
    "Source Type HQ Employee" text NULL,
    "Source Link HQ Employee" text NULL,
    "Comments CD" text NULL,
    "Year" text NULL,
    "Entry year of GCC" text NULL
  );
