CREATE TABLE
  public.services (
    last_update_date text NULL,
    account_global_legal_name text NULL,
    cn_unique_key text NULL,
    key text NULL,
    center_legal_name text NULL,
    center_type text NULL,
    center_focus text NULL,
    center_souce_link text NULL,
    city text NULL,
    primary_services_foucs text NULL,
    primary_services_source text NULL,
    focus_region text NULL,
    focus_region_source_link text NULL,
    it text NULL,
    it_source_link text NULL,
    erd text NULL,
    engineering_source_link text NULL,
    fna text NULL,
    fna_source_link text NULL,
    hr text NULL,
    hr_source_link text NULL,
    procurement_and_supply_chain text NULL,
    procurement_and_supply_chain_source_link text NULL,
    sales_and_marketing text NULL,
    sales_and_marketing_source_link text NULL,
    customer_services text NULL,
    customer_services_source_link text NULL,
    other_service text NULL,
    other_source_link text NULL,
    software_vendor text NULL,
    software_in_use text NULL,
    software_source_link text NULL,
    comments text NULL,
    year text NULL
  );
